### ISSUE TITLE
Handling BTRoblox nav icons

### ISSUE THREAD

**Issue by aubymori** [anthony1x6000/ROBLOX2016stylus#7]
**Is your feature request related to a problem? Please describe.**
The color of the BTR nav icons in the blue header are wrong.

**Describe the feature you'd like**
I'd like these icons to be consistent with the 2016 style.

**Additional context**
Go to line 1764 in the style, and add the `.light-theme #header .btr-nav-notif` selector to it.
(Here's the CSS rule I'm talking about)
```css
.light-theme .notification-red {
    background-color: #e2231a;
    color: #ffffff;
}
```
Also, add this CSS rule.
```css
.light-theme .icon-nav-message-btr,
.light-theme .icon-nav-friend-btr {
    filter: none;
}
```
**Before:**
![image](https://user-images.githubusercontent.com/44238627/137251087-c8758d09-a023-4336-a57a-eade04149f22.png)
After:
![image](https://user-images.githubusercontent.com/44238627/137251109-60fbb37f-7e58-435f-926e-705689b358a6.png)
